class BackupThread extends Thread {
    public void read() throws IOException {
        FileChannel ch = m_pe.getChannel();
        ByteBuffer head = ByteBuffer.allocate(255);
        head.order(ByteOrder.LITTLE_ENDIAN);
        ch.position(m_baseoffset);
        ch.read(head);
        head.position(0);
        int pemagic = head.getInt();
        Machine = head.getShort();
        NumberOfSections = head.getShort();
        TimeDateStamp = head.getInt();
        PointerToSymbolTable = head.getInt();
        NumberOfSymbols = head.getInt();
        SizeOfOptionalHeader = head.getShort();
        Characteristics = head.getShort();
        Magic = head.getShort();
        MajorLinkerVersion = head.get();
        MinorLinkerVersion = head.get();
        SizeOfCode = head.getInt();
        SizeOfInitializedData = head.getInt();
        SizeOfUninitializedData = head.getInt();
        AddressOfEntryPoint = head.getInt();
        BaseOfCode = head.getInt();
        BaseOfData = head.getInt();
        ImageBase = head.getInt();
        SectionAlignment = head.getInt();
        FileAlignment = head.getInt();
        MajorOperatingSystemVersion = head.getShort();
        MinorOperatingSystemVersion = head.getShort();
        MajorImageVersion = head.getShort();
        MinorImageVersion = head.getShort();
        MajorSubsystemVersion = head.getShort();
        MinorSubsystemVersion = head.getShort();
        Reserved1 = head.getInt();
        SizeOfImage = head.getInt();
        SizeOfHeaders = head.getInt();
        CheckSum = head.getInt();
        Subsystem = head.getShort();
        DllCharacteristics = head.getShort();
        SizeOfStackReserve = head.getInt();
        SizeOfStackCommit = head.getInt();
        SizeOfHeapReserve = head.getInt();
        SizeOfHeapCommit = head.getInt();
        LoaderFlags = head.getInt();
        NumberOfRvaAndSizes = head.getInt();
        ExportDirectory_VA = head.getInt();
        ExportDirectory_Size = head.getInt();
        ImportDirectory_VA = head.getInt();
        ImportDirectory_Size = head.getInt();
        ResourceDirectory_VA = head.getInt();
        ResourceDirectory_Size = head.getInt();
        ExceptionDirectory_VA = head.getInt();
        ExceptionDirectory_Size = head.getInt();
        SecurityDirectory_VA = head.getInt();
        SecurityDirectory_Size = head.getInt();
        BaseRelocationTable_VA = head.getInt();
        BaseRelocationTable_Size = head.getInt();
        DebugDirectory_VA = head.getInt();
        DebugDirectory_Size = head.getInt();
        ArchitectureSpecificData_VA = head.getInt();
        ArchitectureSpecificData_Size = head.getInt();
        RVAofGP_VA = head.getInt();
        RVAofGP_Size = head.getInt();
        TLSDirectory_VA = head.getInt();
        TLSDirectory_Size = head.getInt();
        LoadConfigurationDirectory_VA = head.getInt();
        LoadConfigurationDirectory_Size = head.getInt();
        BoundImportDirectoryinheaders_VA = head.getInt();
        BoundImportDirectoryinheaders_Size = head.getInt();
        ImportAddressTable_VA = head.getInt();
        ImportAddressTable_Size = head.getInt();
        DelayLoadImportDescriptors_VA = head.getInt();
        DelayLoadImportDescriptors_Size = head.getInt();
        COMRuntimedescriptor_VA = head.getInt();
        COMRuntimedescriptor_Size = head.getInt();
    }
}
