class BackupThread extends Thread {
    public void fill(String src, String dest, String user) throws IOException, DocumentException {
        PdfReader reader = new PdfReader(src);
        FileOutputStream writer = new FileOutputStream(dest);
        PdfStamper stamper = new PdfStamper(reader, writer);
        stamper.setEncryption(true, "", UUID.randomUUID().toString(), 0);
        AcroFields fields = stamper.getAcroFields();
        Font font = FontFactory.getFont(FontFactory.COURIER_BOLD);
        font.setSize((float) 20.2);
        BaseFont baseFont = font.getBaseFont();
        fields.setFieldProperty("AngelVenture CurrentYearContribution", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AngelVenture CurrentYearContribution", "textfont", baseFont, null);
        fields.setField("AngelVenture CurrentYearContribution", this.get_AngelVenture_CurrentYearContribution());
        fields.setFieldProperty("ElderlyDisabledCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ElderlyDisabledCredit", "textfont", baseFont, null);
        fields.setField("ElderlyDisabledCredit", this.get_ElderlyDisabledCredit());
        fields.setFieldProperty("TotalAdditionsToVtTax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalAdditionsToVtTax", "textfont", baseFont, null);
        fields.setField("TotalAdditionsToVtTax", this.get_TotalAdditionsToVtTax());
        fields.setFieldProperty("AgeQuestion", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AgeQuestion", "textfont", baseFont, null);
        fields.setField("AgeQuestion", this.get_AgeQuestion());
        fields.setFieldProperty("FEINOfEntity", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FEINOfEntity", "textfont", baseFont, null);
        fields.setField("FEINOfEntity", this.get_FEINOfEntity());
        fields.setFieldProperty("VtHighEdInvestment CreditAmount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VtHighEdInvestment CreditAmount", "textfont", baseFont, null);
        fields.setField("VtHighEdInvestment CreditAmount", this.get_VtHighEdInvestment_CreditAmount());
        fields.setFieldProperty("CreditTaxPaidOtherState", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CreditTaxPaidOtherState", "textfont", baseFont, null);
        fields.setField("CreditTaxPaidOtherState", this.get_CreditTaxPaidOtherState());
        fields.setFieldProperty("FedForm4972Tax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FedForm4972Tax", "textfont", baseFont, null);
        fields.setField("FedForm4972Tax", this.get_FedForm4972Tax());
        fields.setFieldProperty("AdjustedGrossIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AdjustedGrossIncome", "textfont", baseFont, null);
        fields.setField("AdjustedGrossIncome", this.get_AdjustedGrossIncome());
        fields.setFieldProperty("QualifiedSaleMobileHomePark CreditAmount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("QualifiedSaleMobileHomePark CreditAmount", "textfont", baseFont, null);
        fields.setField("QualifiedSaleMobileHomePark CreditAmount", this.get_QualifiedSaleMobileHomePark_CreditAmount());
        fields.setFieldProperty("SubtractoinsFromVtTax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("SubtractoinsFromVtTax", "textfont", baseFont, null);
        fields.setField("SubtractoinsFromVtTax", this.get_SubtractoinsFromVtTax());
        fields.setFieldProperty("VTSubtractionSubtotal", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTSubtractionSubtotal", "textfont", baseFont, null);
        fields.setField("VTSubtractionSubtotal", this.get_VTSubtractionSubtotal());
        fields.setFieldProperty("RecaptureVtCredits", "textsize", new Float(20.2), null);
        fields.setFieldProperty("RecaptureVtCredits", "textfont", baseFont, null);
        fields.setField("RecaptureVtCredits", this.get_RecaptureVtCredits());
        fields.setFieldProperty("QualifiedPlansTax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("QualifiedPlansTax", "textfont", baseFont, null);
        fields.setField("QualifiedPlansTax", this.get_QualifiedPlansTax());
        fields.setFieldProperty("EICFederalAmt", "textsize", new Float(20.2), null);
        fields.setFieldProperty("EICFederalAmt", "textfont", baseFont, null);
        fields.setField("EICFederalAmt", this.get_EICFederalAmt());
        fields.setFieldProperty("VTBusSolarEnergyCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTBusSolarEnergyCredit", "textfont", baseFont, null);
        fields.setField("VTBusSolarEnergyCredit", this.get_VTBusSolarEnergyCredit());
        fields.setFieldProperty("VermontTotalEarnedIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VermontTotalEarnedIncome", "textfont", baseFont, null);
        fields.setField("VermontTotalEarnedIncome", this.get_VermontTotalEarnedIncome());
        fields.setFieldProperty("RecaptureFederalInvCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("RecaptureFederalInvCredit", "textfont", baseFont, null);
        fields.setField("RecaptureFederalInvCredit", this.get_RecaptureFederalInvCredit());
        fields.setFieldProperty("TotalSubtractoinsFromVtTax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalSubtractoinsFromVtTax", "textfont", baseFont, null);
        fields.setField("TotalSubtractoinsFromVtTax", this.get_TotalSubtractoinsFromVtTax());
        fields.setFieldProperty("CharitableHousing CarryForward", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CharitableHousing CarryForward", "textfont", baseFont, null);
        fields.setField("CharitableHousing CarryForward", this.get_CharitableHousing_CarryForward());
        fields.setFieldProperty("ComputedTaxCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ComputedTaxCredit", "textfont", baseFont, null);
        fields.setField("ComputedTaxCredit", this.get_ComputedTaxCredit());
        fields.setFieldProperty("VtHighEdInvestment CurrentYearContribution", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VtHighEdInvestment CurrentYearContribution", "textfont", baseFont, null);
        fields.setField("VtHighEdInvestment CurrentYearContribution", this.get_VtHighEdInvestment_CurrentYearContribution());
        fields.setFieldProperty("CharitableHousing Earned", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CharitableHousing Earned", "textfont", baseFont, null);
        fields.setField("CharitableHousing Earned", this.get_CharitableHousing_Earned());
        fields.setFieldProperty("Text232", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text232", "textfont", baseFont, null);
        fields.setField("Text232", this.get_Text232());
        fields.setFieldProperty("NameOfEntity", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NameOfEntity", "textfont", baseFont, null);
        fields.setField("NameOfEntity", this.get_NameOfEntity());
        fields.setFieldProperty("BusinessSolarEnergyNewCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("BusinessSolarEnergyNewCredit", "textfont", baseFont, null);
        fields.setField("BusinessSolarEnergyNewCredit", this.get_BusinessSolarEnergyNewCredit());
        fields.setFieldProperty("IncomeTaxableToBoth", "textsize", new Float(20.2), null);
        fields.setFieldProperty("IncomeTaxableToBoth", "textfont", baseFont, null);
        fields.setField("IncomeTaxableToBoth", this.get_IncomeTaxableToBoth());
        fields.setFieldProperty("NetTaxPaidToOtherState", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NetTaxPaidToOtherState", "textfont", baseFont, null);
        fields.setField("NetTaxPaidToOtherState", this.get_NetTaxPaidToOtherState());
        fields.setFieldProperty("FarmIncAveragingCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FarmIncAveragingCredit", "textfont", baseFont, null);
        fields.setField("FarmIncAveragingCredit", this.get_FarmIncAveragingCredit());
        fields.setFieldProperty("AdditionsSubTotal", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AdditionsSubTotal", "textfont", baseFont, null);
        fields.setField("AdditionsSubTotal", this.get_AdditionsSubTotal());
        fields.setFieldProperty("VTPortionWages", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTPortionWages", "textfont", baseFont, null);
        fields.setField("VTPortionWages", this.get_VTPortionWages());
        fields.setFieldProperty("NameOtherState", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NameOtherState", "textfont", baseFont, null);
        fields.setField("NameOtherState", this.get_NameOtherState());
        fields.setFieldProperty("QualifiedSaleMobileHomePark CarryForward", "textsize", new Float(20.2), null);
        fields.setFieldProperty("QualifiedSaleMobileHomePark CarryForward", "textfont", baseFont, null);
        fields.setField("QualifiedSaleMobileHomePark CarryForward", this.get_QualifiedSaleMobileHomePark_CarryForward());
        fields.setFieldProperty("ChildAndDependentCareExp", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ChildAndDependentCareExp", "textfont", baseFont, null);
        fields.setField("ChildAndDependentCareExp", this.get_ChildAndDependentCareExp());
        fields.setFieldProperty("EICAdjustment", "textsize", new Float(20.2), null);
        fields.setFieldProperty("EICAdjustment", "textfont", baseFont, null);
        fields.setField("EICAdjustment", this.get_EICAdjustment());
        fields.setFieldProperty("CreditTotal", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CreditTotal", "textfont", baseFont, null);
        fields.setField("CreditTotal", this.get_CreditTotal());
        fields.setFieldProperty("VTLocalStateObligations", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTLocalStateObligations", "textfont", baseFont, null);
        fields.setField("VTLocalStateObligations", this.get_VTLocalStateObligations());
        fields.setFieldProperty("VTAdditions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTAdditions", "textfont", baseFont, null);
        fields.setField("VTAdditions", this.get_VTAdditions());
        fields.setFieldProperty("FederalWages", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FederalWages", "textfont", baseFont, null);
        fields.setField("FederalWages", this.get_FederalWages());
        fields.setFieldProperty("EarnedIncomeCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("EarnedIncomeCredit", "textfont", baseFont, null);
        fields.setField("EarnedIncomeCredit", this.get_EarnedIncomeCredit());
        fields.setFieldProperty("NonVTLocalStateObligations", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NonVTLocalStateObligations", "textfont", baseFont, null);
        fields.setField("NonVTLocalStateObligations", this.get_NonVTLocalStateObligations());
        fields.setFieldProperty("TotalLocalStateObligations", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalLocalStateObligations", "textfont", baseFont, null);
        fields.setField("TotalLocalStateObligations", this.get_TotalLocalStateObligations());
        fields.setFieldProperty("EICNumQualChildren", "textsize", new Float(20.2), null);
        fields.setFieldProperty("EICNumQualChildren", "textfont", baseFont, null);
        fields.setField("EICNumQualChildren", this.get_EICNumQualChildren());
        fields.setFieldProperty("QualifiedSaleMobileHomePark Earned", "textsize", new Float(20.2), null);
        fields.setFieldProperty("QualifiedSaleMobileHomePark Earned", "textfont", baseFont, null);
        fields.setField("QualifiedSaleMobileHomePark Earned", this.get_QualifiedSaleMobileHomePark_Earned());
        fields.setFieldProperty("VermontOtherEarnedIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VermontOtherEarnedIncome", "textfont", baseFont, null);
        fields.setField("VermontOtherEarnedIncome", this.get_VermontOtherEarnedIncome());
        fields.setFieldProperty("CharitableHousing CreditAmount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CharitableHousing CreditAmount", "textfont", baseFont, null);
        fields.setField("CharitableHousing CreditAmount", this.get_CharitableHousing_CreditAmount());
        fields.setFieldProperty("AngelVenture CreditAmount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AngelVenture CreditAmount", "textfont", baseFont, null);
        fields.setField("AngelVenture CreditAmount", this.get_AngelVenture_CreditAmount());
        fields.setFieldProperty("FederalTotalEarnedIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FederalTotalEarnedIncome", "textfont", baseFont, null);
        fields.setField("FederalTotalEarnedIncome", this.get_FederalTotalEarnedIncome());
        fields.setFieldProperty("InvestmentTaxCredit", "textsize", new Float(20.2), null);
        fields.setFieldProperty("InvestmentTaxCredit", "textfont", baseFont, null);
        fields.setField("InvestmentTaxCredit", this.get_InvestmentTaxCredit());
        fields.setFieldProperty("VTIncomeTax", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTIncomeTax", "textfont", baseFont, null);
        fields.setField("VTIncomeTax", this.get_VTIncomeTax());
        fields.setFieldProperty("BusinessSolarEnergyCarryforward", "textsize", new Float(20.2), null);
        fields.setFieldProperty("BusinessSolarEnergyCarryforward", "textfont", baseFont, null);
        fields.setField("BusinessSolarEnergyCarryforward", this.get_BusinessSolarEnergyCarryforward());
        fields.setFieldProperty("VTEICCreditSubtotal", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTEICCreditSubtotal", "textfont", baseFont, null);
        fields.setField("VTEICCreditSubtotal", this.get_VTEICCreditSubtotal());
        fields.setFieldProperty("CommercialFilm CreditAmount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CommercialFilm CreditAmount", "textfont", baseFont, null);
        fields.setField("CommercialFilm CreditAmount", this.get_CommercialFilm_CreditAmount());
        fields.setFieldProperty("CommercialFilm Earned", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CommercialFilm Earned", "textfont", baseFont, null);
        fields.setField("CommercialFilm Earned", this.get_CommercialFilm_Earned());
        fields.setFieldProperty("FederalOtherEarnedIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FederalOtherEarnedIncome", "textfont", baseFont, null);
        fields.setField("FederalOtherEarnedIncome", this.get_FederalOtherEarnedIncome());
        stamper.setFormFlattening(true);
        stamper.setFullCompression();
        for (int i = 0; i < reader.getNumberOfPages() + 1; i++) {
            PdfContentByte overContent = stamper.getOverContent(i);
            if (overContent != null) {
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES_ITALIC);
                font.setColor(BaseColor.BLUE);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.BLUE);
                overContent.setFontAndSize(baseFont, 24);
                overContent.showTextAligned(Element.ALIGN_RIGHT | Element.ALIGN_TOP, "Electronically filed via Modernized eFile", 20, 175, 90);
                overContent.endText();
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES);
                font.setColor(BaseColor.RED);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.RED);
                overContent.setFontAndSize(baseFont, 8);
                overContent.showTextAligned(Element.ALIGN_CENTER | Element.ALIGN_BOTTOM, "Retrieved by " + user + " on " + new Date().toString(), 220, 3, 0);
                overContent.endText();
            }
        }
        stamper.close();
        reader.close();
    }
}
