class BackupThread extends Thread {
    public TeachMasterLang() {
        resources.put("ok", "OK");
        resources.put("abort", "Abort");
        resources.put("back", "Back");
        resources.put("exit", "Exit");
        resources.put("about", "About");
        resources.put("start", "Start");
        resources.put("answer", "Answer");
        resources.put("help", "Help");
        resources.put("abort", "Abort");
        resources.put("repeat", "Repeat");
        resources.put("accept", "Accept");
        resources.put("properties", "Properties");
        resources.put("info", "Info");
        resources.put("error", "Error");
        resources.put("not_authorized", "You are not authorized to access the restricted API");
        resources.put("no_access", "Cannot access FileConnection");
        resources.put("wrong_permission", "You cannot browse your phone directories with the current permissions. Exit the application, and change the security attributes for it");
        resources.put("not_exist", "File does not exists");
        resources.put("no_access_file", "Can not access File");
        resources.put("in_directory", "in directory");
        resources.put("methodpatiencenotready", "Method \"patience\" is not implemented yet \n\n:-(");
        resources.put("novok2file", "No \".vok2\" read... \n\n" + "Maybe you haven't located your \".vok2\" file.\n\n" + "Or maybe you haven't allow the application" + " to read and write data.");
        resources.put("noword", "No word in this lesson...");
        resources.put("notimplementedyet", "Not implemented yet \n\n:-(");
        resources.put("restartapplication", "you need to restart the program\n\n :-(");
        resources.put("learn", "Learn Process");
        resources.put("statistics", "Statistics");
        resources.put("settings", "Settings");
        resources.put("language", "Language");
        resources.put("fileinfo", "\".vok2\" file info");
        resources.put("findfile", "Find \".vok2\" file");
        resources.put("languagetitle", "Language");
        resources.put("langgrpbox", " Application language ");
        resources.put("english", "English");
        resources.put("french", "Fran�ais");
        resources.put("german", "Deutsch");
        resources.put("fileinfotitle", "\".vok2\" File Info");
        resources.put("file", "File");
        resources.put("filetitle", "Title");
        resources.put("author", "Author");
        resources.put("language1", "Language 1");
        resources.put("language2", "Language 2");
        resources.put("nbroflesson", "Lessons");
        resources.put("nbrofwords", "Words");
        resources.put("by", " by ");
        resources.put("jan", "Jan");
        resources.put("feb", "Feb");
        resources.put("mar", "Mar");
        resources.put("apr", "Apr");
        resources.put("may", "May");
        resources.put("jun", "Jun");
        resources.put("jul", "Jul");
        resources.put("aug", "Aug");
        resources.put("sep", "Sep");
        resources.put("oct", "Oct");
        resources.put("nov", "Nov");
        resources.put("dec", "Dec");
        resources.put("location", "Location");
        resources.put("modified", "Modified");
        resources.put("selectlessontitle", "Start Lesson");
        resources.put("lessontolearn", "Select Lesson");
        resources.put("learnsens", "Learning direction");
        resources.put("from", "from");
        resources.put("to", "to");
        resources.put("learnmethode", "Learn method");
        resources.put("classic", "classic");
        resources.put("patience", "patience");
        resources.put("learntitle", "Learn");
        resources.put("eoflearn", "End of learn process");
        resources.put("totalwords", "Number of words: ");
        resources.put("correctanswers", "Correct answers: ");
        resources.put("wronganswers", "Wrong answers:   ");
        resources.put("congratulations", "Congratulations !");
        resources.put("notsobad", "Not so bad");
        resources.put("needpractice", "Need practice !");
        resources.put("smileexcellent", ";-)");
        resources.put("wordinbox1", "Words in Box 1");
        resources.put("wordinbox2", "Words in Box 2");
        resources.put("wordinbox3", "Words in Box 3");
        resources.put("wordinbox4", "Words in Box 4");
        resources.put("wordinbox5", "Words in Box 5");
    }
}
