class BackupThread extends Thread {
    public void fill(String src, String dest, String user) throws IOException, DocumentException {
        PdfReader reader = new PdfReader(src);
        FileOutputStream writer = new FileOutputStream(dest);
        PdfStamper stamper = new PdfStamper(reader, writer);
        stamper.setEncryption(true, "", "Gu7ruc*YAWaStEbr", 0);
        AcroFields fields = stamper.getAcroFields();
        Font font = FontFactory.getFont(FontFactory.COURIER_BOLD);
        font.setSize((float) 20.2);
        BaseFont baseFont = font.getBaseFont();
        fields.setFieldProperty("CashPublicAssistance", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CashPublicAssistance", "textfont", baseFont, null);
        fields.setField("CashPublicAssistance", this.get_CashPublicAssistance());
        fields.setFieldProperty("TotalIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalIncome", "textfont", baseFont, null);
        fields.setField("TotalIncome", this.get_TotalIncome());
        fields.setFieldProperty("Wages", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Wages", "textfont", baseFont, null);
        fields.setField("Wages", this.get_Wages());
        fields.setFieldProperty("FederalAdjustments", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FederalAdjustments", "textfont", baseFont, null);
        fields.setField("FederalAdjustments", this.get_FederalAdjustments());
        fields.setFieldProperty("OtherPersonsNameSSN", "textsize", new Float(20.2), null);
        fields.setFieldProperty("OtherPersonsNameSSN", "textfont", baseFont, null);
        fields.setField("OtherPersonsNameSSN", this.get_OtherPersonsNameSSN());
        fields.setFieldProperty("AlimonySupport", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AlimonySupport", "textfont", baseFont, null);
        fields.setField("AlimonySupport", this.get_AlimonySupport());
        fields.setFieldProperty("RentalIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("RentalIncome", "textfont", baseFont, null);
        fields.setField("RentalIncome", this.get_RentalIncome());
        fields.setFieldProperty("SSMedicareWithheld", "textsize", new Float(20.2), null);
        fields.setFieldProperty("SSMedicareWithheld", "textfont", baseFont, null);
        fields.setField("SSMedicareWithheld", this.get_SSMedicareWithheld());
        fields.setFieldProperty("Text1", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text1", "textfont", baseFont, null);
        fields.setField("Text1", this.get_Text1());
        fields.setFieldProperty("IncomeUSObligations", "textsize", new Float(20.2), null);
        fields.setFieldProperty("IncomeUSObligations", "textfont", baseFont, null);
        fields.setField("IncomeUSObligations", this.get_IncomeUSObligations());
        fields.setFieldProperty("ChildSupportPaid", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ChildSupportPaid", "textfont", baseFont, null);
        fields.setField("ChildSupportPaid", this.get_ChildSupportPaid());
        fields.setFieldProperty("InterestDividends", "textsize", new Float(20.2), null);
        fields.setFieldProperty("InterestDividends", "textfont", baseFont, null);
        fields.setField("InterestDividends", this.get_InterestDividends());
        fields.setFieldProperty("UnemployWorkersComp", "textsize", new Float(20.2), null);
        fields.setFieldProperty("UnemployWorkersComp", "textfont", baseFont, null);
        fields.setField("UnemployWorkersComp", this.get_UnemployWorkersComp());
        fields.setFieldProperty("Text119", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text119", "textfont", baseFont, null);
        fields.setField("Text119", this.get_Text119());
        fields.setFieldProperty("Pensions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Pensions", "textfont", baseFont, null);
        fields.setField("Pensions", this.get_Pensions());
        fields.setFieldProperty("AdjustedIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AdjustedIncome", "textfont", baseFont, null);
        fields.setField("AdjustedIncome", this.get_AdjustedIncome());
        fields.setFieldProperty("TotalAdjustments", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalAdjustments", "textfont", baseFont, null);
        fields.setField("TotalAdjustments", this.get_TotalAdjustments());
        fields.setFieldProperty("CapitalGain", "textsize", new Float(20.2), null);
        fields.setFieldProperty("CapitalGain", "textfont", baseFont, null);
        fields.setField("CapitalGain", this.get_CapitalGain());
        fields.setFieldProperty("BusinessIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("BusinessIncome", "textfont", baseFont, null);
        fields.setField("BusinessIncome", this.get_BusinessIncome());
        fields.setFieldProperty("SocialSecurityRailRoadBenefits", "textsize", new Float(20.2), null);
        fields.setFieldProperty("SocialSecurityRailRoadBenefits", "textfont", baseFont, null);
        fields.setField("SocialSecurityRailRoadBenefits", this.get_SocialSecurityRailRoadBenefits());
        fields.setFieldProperty("Text117", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text117", "textfont", baseFont, null);
        fields.setField("Text117", this.get_Text117());
        fields.setFieldProperty("Text118", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text118", "textfont", baseFont, null);
        fields.setField("Text118", this.get_Text118());
        fields.setFieldProperty("FarmPartnerships", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FarmPartnerships", "textfont", baseFont, null);
        fields.setField("FarmPartnerships", this.get_FarmPartnerships());
        fields.setFieldProperty("OtherIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("OtherIncome", "textfont", baseFont, null);
        fields.setField("OtherIncome", this.get_OtherIncome());
        fields.setFieldProperty("TotalHouseholdIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalHouseholdIncome", "textfont", baseFont, null);
        fields.setField("TotalHouseholdIncome", this.get_TotalHouseholdIncome());
        stamper.setFormFlattening(true);
        stamper.setFullCompression();
        for (int i = 0; i < reader.getNumberOfPages() + 1; i++) {
            PdfContentByte overContent = stamper.getOverContent(i);
            if (overContent != null) {
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES_ITALIC);
                font.setColor(BaseColor.BLUE);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.BLUE);
                overContent.setFontAndSize(baseFont, 24);
                overContent.showTextAligned(Element.ALIGN_RIGHT | Element.ALIGN_TOP, "Electronically filed via Modernized eFile", 20, 175, 90);
                overContent.endText();
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES);
                font.setColor(BaseColor.RED);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.RED);
                overContent.setFontAndSize(baseFont, 8);
                overContent.showTextAligned(Element.ALIGN_CENTER | Element.ALIGN_BOTTOM, "Retrieved by " + user + " on " + new Date().toString(), 220, 3, 0);
                overContent.endText();
            }
        }
        stamper.close();
        reader.close();
    }
}
