class BackupThread extends Thread {
    public void _jspService(HttpServletRequest request, HttpServletResponse response) throws java.io.IOException, ServletException {
        PageContext pageContext = null;
        HttpSession session = null;
        ServletContext application = null;
        ServletConfig config = null;
        JspWriter out = null;
        Object page = this;
        JspWriter _jspx_out = null;
        PageContext _jspx_page_context = null;
        try {
            response.setContentType("text/html; charset=ISO-8859-1");
            pageContext = _jspxFactory.getPageContext(this, request, response, null, true, 8192, true);
            _jspx_page_context = pageContext;
            application = pageContext.getServletContext();
            config = pageContext.getServletConfig();
            session = pageContext.getSession();
            out = pageContext.getOut();
            _jspx_out = out;
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script src=\"./js/jQuery.js\" type=\"text/javascript\"></script>\r\n");
            out.write("<script src=\"./js/jquery.maskedinput.js\" type=\"text/javascript\"></script>\r\n");
            out.write("<script src=\"./js/jquery.tablesorter.js\" type=\"text/javascript\"></script>\r\n");
            out.write("\r\n");
            out.write("<!--  para o auto complete -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, true);
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script>\r\n");
            out.write("\tfunction salvar() {\r\n");
            out.write("\t\tvar form = document.forms[0];\r\n");
            out.write("\t\tform.metodo.value = 'salvar';\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tif(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not formCadastroServico.editavel}", java.lang.String.class, (PageContext) _jspx_page_context, null, false));
            out.write("){\r\n");
            out.write("\t\t\tform.metodo.value = 'editar';\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\tform.submit();\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction adicionar(){\r\n");
            out.write("\t\tvar form = document.forms[0];\r\n");
            out.write("\t\tform.metodo.value = 'add';\r\n");
            out.write("\t\tform.submit();\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\tfunction editar() {\r\n");
            out.write("\t\tvar form = document.forms[0];\r\n");
            out.write("\t\tform.metodo.value = 'editar';\r\n");
            out.write("\t\tform.submit();\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\r\n");
            out.write("\tfunction carregarMascaras() {\r\n");
            out.write("\t\tdocument.formCadastroServico.reset();\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tvalorMask = new Mask(\"#.00\", \"number\");\r\n");
            out.write("\t\tvalorMask.attach(document.formCadastroServico.valor);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tquantidadeParcelasMask = new Mask(\"#\", \"number\");\r\n");
            out.write("\t\tquantidadeParcelasMask.attach(document.formCadastroServico.quantidadeParcelas);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tmesMask = new Mask(\"##\", \"number\");\r\n");
            out.write("\t\tmesMask.attach(document.formCadastroServico.mesVencimentoPrimeiraParcela);\r\n");
            out.write("\t\tmesMask.attach(document.formCadastroServico.mesIsencao);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tanoMask = new Mask(\"####\", \"number\");\r\n");
            out.write("\t\tanoMask.attach(document.formCadastroServico.anoVencimentoPrimeiraParcela);\r\n");
            out.write("\t\tanoMask.attach(document.formCadastroServico.anoIsencao);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tmesMask.attach(document.formCadastroServico.quantidadePrimeirasParcelas);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tmesMask.attach(document.formCadastroServico.campoQuantidadeParcelas);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tvalorMask.attach(document.formCadastroServico.campoValorTotal);\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\tvalorMask.attach(document.formCadastroServico.valorPrimeirasParcelas);\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\tfunction inicializaCombo(){\r\n");
            out.write("\t\tvar a = document.getElementById('tipo').value;\r\n");
            out.write("\t\tif(document.getElementById('radioTipoServico') != null){\r\n");
            out.write("\t\t\tdocument.forms[0].radioTipoServico[a].checked = 1;\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction esconde(){\r\n");
            out.write("\t\tfor(i =0; i <= 4; i++){\r\n");
            out.write("\t\t\tif(document.getElementById('radioTipoServico') != null){\r\n");
            out.write("\t\t\t\tif(document.forms[0].radioTipoServico[i].checked){\r\n");
            out.write("\t\t\t\t\tdocument.getElementById('tipo').value = i;\r\n");
            out.write("\t\t\t\t}\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tif(document.getElementById('tipo').value == 3){\r\n");
            out.write("\t\t\tdocument.getElementById('parcelasDiv').style.display='none';\r\n");
            out.write("\t\t\tdocument.getElementById('descricao').style.display='none';\r\n");
            out.write("\t\t}else if(document.getElementById('tipo').value == 4){\r\n");
            out.write("\t\t\tdocument.getElementById('descricao').style.display='block';\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("\tfunction mudaOpcao(){\r\n");
            out.write("\t\tfor(i =0; i <= 4; i++){\r\n");
            out.write("\t\t\tif(document.forms[0].radioTipoServico[i].checked){\r\n");
            out.write("\t\t\t\tdocument.getElementById('tipo').value = i;\r\n");
            out.write("\t\t\t\t//alert(i);\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t} \r\n");
            out.write("\t\tif(document.forms[0].radioTipoServico[3].checked){\r\n");
            out.write("\t\t\t//document.getElementById('campoQuantidadeParcelas').style.display='none';\r\n");
            out.write("\t\t//\tdocument.getElementById('labelparcelas').style.display='none';\r\n");
            out.write("\t\t\tdocument.getElementById('parcelasDiv').style.display='none';\r\n");
            out.write("\t\t\tdocument.getElementById('valorMensal').style.display='block';\r\n");
            out.write("\t\t\tdocument.getElementById('valorTotal').style.display='none';\r\n");
            out.write("\t\t\tdocument.getElementById('manutencao').style.display='block';\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t//\tdocument.getElementById('labelparcelas').style.display='block';\r\n");
            out.write("\t\t\t//document.getElementById('campoQuantidadeParcelas').style.display='block';\r\n");
            out.write("\t\t\tdocument.getElementById('parcelasDiv').style.display='block';\r\n");
            out.write("\t\t\tdocument.getElementById('valorMensal').style.display='none';\r\n");
            out.write("\t\t\tdocument.getElementById('valorTotal').style.display='block';\r\n");
            out.write("\t\t\tdocument.getElementById('manutencao').style.display='none';\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\t\r\n");
            out.write("\t\tif(document.forms[0].radioTipoServico[4].checked){\r\n");
            out.write("\t\t\tdocument.getElementById('descricao').style.display='block';\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t\tdocument.getElementById('descricao').style.display='none';\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction inicializaPaciente(){\r\n");
            out.write("\t\tdocument.getElementById('model').value = document.getElementById('nomePaciente').value;\r\n");
            out.write("\t\tif(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not formCadastroServico.editavel}", java.lang.String.class, (PageContext) _jspx_page_context, null, false));
            out.write("){\r\n");
            out.write("\t\t\tdocument.getElementById('model').disabled = 1;\r\n");
            out.write("\t\t\tdocument.getElementById('radioTipoServico').disabled = 1;\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t\tfor(i =0; i <= 4; i++){\r\n");
            out.write("\t\t\t   document.forms[0].radioTipoServico[i].disabled = 1;\t\r\n");
            out.write("\t\t\t} \r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t\tdocument.getElementById('model').disabled = 0;\r\n");
            out.write("\t\t\tdocument.getElementById('radioTipoServico').disabled = 0;\r\n");
            out.write("\t\t\tfor(i =0; i <= 4; i++){\r\n");
            out.write("\t\t\t   document.forms[0].radioTipoServico[i].disabled = 0;\t\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction abrir(aURL, W, L) {\r\n");
            out.write("  \t\twindow.open(aURL,'Ler', 'width='+W+', height='+L+', top=0, left=0, scrollbars=yes, status=no, toolbar=no, location=no, directories=no, menubar=no, resizable=no, fullscreen=no');\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction exibirParteEdicao(){\r\n");
            out.write("\t\tif(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formCadastroServico.editavel}", java.lang.String.class, (PageContext) _jspx_page_context, null, false));
            out.write("){\r\n");
            out.write("\t\t\tdocument.getElementById('parteEdicao').style.display = 'none';\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t\tdocument.getElementById('parteEdicao').style.display = 'block';\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction exibirCamposIsentar(){\r\n");
            out.write("\t\tif(document.getElementById('isentar').checked == true){\r\n");
            out.write("\t\t\tdocument.getElementById('divIsentar').style.display='block';\r\n");
            out.write("\t\t\tif(document.getElementById('mesIsencao').value == '' || document.getElementById('mesIsencao').value == 0){\r\n");
            out.write("\t\t\t\tdocument.getElementById('mesIsencao').value = '';\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t\tif(document.getElementById('anoIsencao').value == '' || document.getElementById('anoIsencao').value == 0){\r\n");
            out.write("\t\t\t\tdocument.getElementById('anoIsencao').value = '';\r\n");
            out.write("\t\t\t}\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t\tdocument.getElementById('divIsentar').style.display='none';\r\n");
            out.write("\t\t}\r\n");
            out.write("\t\t\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction isentar(){\r\n");
            out.write("\t\tif(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formCadastroServico.linkIsentar}", java.lang.String.class, (PageContext) _jspx_page_context, null, false));
            out.write("){\r\n");
            out.write("\t\t\tvar form = document.forms[0];\r\n");
            out.write("\t\t\tform.metodo.value = 'isentar';\r\n");
            out.write("\t\t\tform.submit();\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t   alert('O Serviço não pode ser isentado, porque já foi isentado ou está sendo cadastrado.');\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\tfunction limpar(obj){\r\n");
            out.write("\t\tif(obj.value == '' || obj.value == null){\r\n");
            out.write("\t\t\tdocument.getElementById('pacienteId').value = '';\r\n");
            out.write("\t\t\tdocument.getElementById('nomePaciente').value = '';\r\n");
            out.write("\t\t}else{\r\n");
            out.write("\t\t\tdocument.getElementById('nomePaciente').value = obj.value;\r\n");
            out.write("\t\t}\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t\r\n");
            out.write("</script>\r\n");
            out.write("\t\r\n");
            out.write("\r\n");
            out.write("<div id=\"corpo\">\r\n");
            out.write("\r\n");
            out.write("<div class=\"breadcrumb\">\r\n");
            out.write("\t");
            if (_jspx_meth_html_005flink_005f0(_jspx_page_context)) return;
            out.write("\r\n");
            out.write("\t\t&raquo;  ");
            if (_jspx_meth_html_005flink_005f1(_jspx_page_context)) return;
            out.write("\r\n");
            out.write("\t\t&raquo;<a class=\"ativo\" href=\"#\">Cadastro de Serviço Particular</a> </div>\r\n");
            if (_jspx_meth_html_005fform_005f0(_jspx_page_context)) return;
            out.write("\r\n");
            out.write("</div>");
        } catch (Throwable t) {
            if (!(t instanceof SkipPageException)) {
                out = _jspx_out;
                if (out != null && out.getBufferSize() != 0) try {
                    out.clearBuffer();
                } catch (java.io.IOException e) {
                }
                if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
            }
        } finally {
            _jspxFactory.releasePageContext(_jspx_page_context);
        }
    }
}
