class BackupThread extends Thread {
    public void exportTo(String file_name, XBookmarkFolder root_folder) throws Exception {
        FileWriter file_writer = new FileWriter(file_name);
        String title = "Bookmarks generated by " + XProjectConstants.PRODUCT_NAME;
        file_writer.write("<!DOCTYPE NETSCAPE-Bookmark-file-1>\n");
        file_writer.write("<!-- This is an automatically generated file.\n");
        file_writer.write("It will be read and overwritten.\n");
        file_writer.write("Do Not Edit! -->\n");
        file_writer.write("<TITLE>" + title + "</TITLE>\n");
        file_writer.write("<H1>" + title + "</H1>\n\n\n");
        file_writer.write("<DL><p>\n\n");
        Iterator bookmarks = root_folder.getBookmarks();
        while (bookmarks.hasNext()) saveBookmarksImpl((XAbstractBookmark) bookmarks.next(), file_writer, "\t");
        file_writer.write("</DL><p>\n\n");
        try {
            file_writer.close();
        } catch (Exception e) {
        }
    }
}
