class BackupThread extends Thread {
    public void fill(String src, String dest, String user) throws IOException, DocumentException {
        PdfReader reader = new PdfReader(src);
        FileOutputStream writer = new FileOutputStream(dest);
        PdfStamper stamper = new PdfStamper(reader, writer);
        stamper.setEncryption(true, "", "Gu7ruc*YAWaStEbr", 0);
        AcroFields fields = stamper.getAcroFields();
        Font font = FontFactory.getFont(FontFactory.COURIER_BOLD);
        font.setSize((float) 20.2);
        BaseFont baseFont = font.getBaseFont();
        fields.setFieldProperty("Federal EducatorExpenses", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal EducatorExpenses", "textfont", baseFont, null);
        fields.setField("Federal EducatorExpenses", this.get_Federal_EducatorExpenses());
        fields.setFieldProperty("NonresidentCommericalFilm", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NonresidentCommericalFilm", "textfont", baseFont, null);
        fields.setField("NonresidentCommericalFilm", this.get_NonresidentCommericalFilm());
        fields.setFieldProperty("ResidentFromDate", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ResidentFromDate", "textfont", baseFont, null);
        fields.setField("ResidentFromDate", this.get_ResidentFromDate());
        fields.setFieldProperty("DisabledPersonSupport", "textsize", new Float(20.2), null);
        fields.setFieldProperty("DisabledPersonSupport", "textfont", baseFont, null);
        fields.setField("DisabledPersonSupport", this.get_DisabledPersonSupport());
        fields.setFieldProperty("Federal MovingExpenses", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal MovingExpenses", "textfont", baseFont, null);
        fields.setField("Federal MovingExpenses", this.get_Federal_MovingExpenses());
        fields.setFieldProperty("ResidentState", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ResidentState", "textfont", baseFont, null);
        fields.setField("ResidentState", this.get_ResidentState());
        fields.setFieldProperty("Vermont TaxableTaxRefunds", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TaxableTaxRefunds", "textfont", baseFont, null);
        fields.setField("Vermont TaxableTaxRefunds", this.get_Vermont_TaxableTaxRefunds());
        fields.setFieldProperty("Federal PartnershipSCorpLLC", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal PartnershipSCorpLLC", "textfont", baseFont, null);
        fields.setField("Federal PartnershipSCorpLLC", this.get_Federal_PartnershipSCorpLLC());
        fields.setFieldProperty("Vermont TaxableSocialSecurity", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TaxableSocialSecurity", "textfont", baseFont, null);
        fields.setField("Vermont TaxableSocialSecurity", this.get_Vermont_TaxableSocialSecurity());
        fields.setFieldProperty("Federal TaxableSocialSecurity", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TaxableSocialSecurity", "textfont", baseFont, null);
        fields.setField("Federal TaxableSocialSecurity", this.get_Federal_TaxableSocialSecurity());
        fields.setFieldProperty("Vermont AlimonyPaid", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont AlimonyPaid", "textfont", baseFont, null);
        fields.setField("Vermont AlimonyPaid", this.get_Vermont_AlimonyPaid());
        fields.setFieldProperty("Vermont Other", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont Other", "textfont", baseFont, null);
        fields.setField("Vermont Other", this.get_Vermont_Other());
        fields.setFieldProperty("Vermont MovingExpenses", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont MovingExpenses", "textfont", baseFont, null);
        fields.setField("Vermont MovingExpenses", this.get_Vermont_MovingExpenses());
        fields.setFieldProperty("Vermont BusinessIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont BusinessIncome", "textfont", baseFont, null);
        fields.setField("Vermont BusinessIncome", this.get_Vermont_BusinessIncome());
        fields.setFieldProperty("IncomeAdjustmentPct", "textsize", new Float(20.2), null);
        fields.setFieldProperty("IncomeAdjustmentPct", "textfont", baseFont, null);
        fields.setField("IncomeAdjustmentPct", this.get_IncomeAdjustmentPct());
        fields.setFieldProperty("ActiveDutyMIlitaryPay", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ActiveDutyMIlitaryPay", "textfont", baseFont, null);
        fields.setField("ActiveDutyMIlitaryPay", this.get_ActiveDutyMIlitaryPay());
        fields.setFieldProperty("Vermont TotalIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TotalIncome", "textfont", baseFont, null);
        fields.setField("Vermont TotalIncome", this.get_Vermont_TotalIncome());
        fields.setFieldProperty("Vermont TaxablePensionsAnnuities", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TaxablePensionsAnnuities", "textfont", baseFont, null);
        fields.setField("Vermont TaxablePensionsAnnuities", this.get_Vermont_TaxablePensionsAnnuities());
        fields.setFieldProperty("ResidentToDate", "textsize", new Float(20.2), null);
        fields.setFieldProperty("ResidentToDate", "textfont", baseFont, null);
        fields.setField("ResidentToDate", this.get_ResidentToDate());
        fields.setFieldProperty("Federal AlimonyReceived", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal AlimonyReceived", "textfont", baseFont, null);
        fields.setField("Federal AlimonyReceived", this.get_Federal_AlimonyReceived());
        fields.setFieldProperty("Federal Other", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal Other", "textfont", baseFont, null);
        fields.setField("Federal Other", this.get_Federal_Other());
        fields.setFieldProperty("TotalNonVtIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("TotalNonVtIncome", "textfont", baseFont, null);
        fields.setField("TotalNonVtIncome", this.get_TotalNonVtIncome());
        fields.setFieldProperty("Federal CapitalGainLoss", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal CapitalGainLoss", "textfont", baseFont, null);
        fields.setField("Federal CapitalGainLoss", this.get_Federal_CapitalGainLoss());
        fields.setFieldProperty("Vermont WagesSalariesTips", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont WagesSalariesTips", "textfont", baseFont, null);
        fields.setField("Vermont WagesSalariesTips", this.get_Vermont_WagesSalariesTips());
        fields.setFieldProperty("Federal TaxableTaxRefunds", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TaxableTaxRefunds", "textfont", baseFont, null);
        fields.setField("Federal TaxableTaxRefunds", this.get_Federal_TaxableTaxRefunds());
        fields.setFieldProperty("Federal AlimonyPaid", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal AlimonyPaid", "textfont", baseFont, null);
        fields.setField("Federal AlimonyPaid", this.get_Federal_AlimonyPaid());
        fields.setFieldProperty("Federal DomesticProductionActivities", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal DomesticProductionActivities", "textfont", baseFont, null);
        fields.setField("Federal DomesticProductionActivities", this.get_Federal_DomesticProductionActivities());
        fields.setFieldProperty("Federal RentsRoyaltiesEstatesTrusts", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal RentsRoyaltiesEstatesTrusts", "textfont", baseFont, null);
        fields.setField("Federal RentsRoyaltiesEstatesTrusts", this.get_Federal_RentsRoyaltiesEstatesTrusts());
        fields.setFieldProperty("Vermont DomesticProductionActivities", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont DomesticProductionActivities", "textfont", baseFont, null);
        fields.setField("Vermont DomesticProductionActivities", this.get_Vermont_DomesticProductionActivities());
        fields.setFieldProperty("Federal TaxablePensionsAnnuities", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TaxablePensionsAnnuities", "textfont", baseFont, null);
        fields.setField("Federal TaxablePensionsAnnuities", this.get_Federal_TaxablePensionsAnnuities());
        fields.setFieldProperty("Federal IRA", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal IRA", "textfont", baseFont, null);
        fields.setField("Federal IRA", this.get_Federal_IRA());
        fields.setFieldProperty("Vermont TaxableInterest", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TaxableInterest", "textfont", baseFont, null);
        fields.setField("Vermont TaxableInterest", this.get_Vermont_TaxableInterest());
        fields.setFieldProperty("VTPortionAGI", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VTPortionAGI", "textfont", baseFont, null);
        fields.setField("VTPortionAGI", this.get_VTPortionAGI());
        fields.setFieldProperty("Vermont RentsRoyaltiesEstatesTrusts", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont RentsRoyaltiesEstatesTrusts", "textfont", baseFont, null);
        fields.setField("Vermont RentsRoyaltiesEstatesTrusts", this.get_Vermont_RentsRoyaltiesEstatesTrusts());
        fields.setFieldProperty("Federal EducationDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal EducationDeductions", "textfont", baseFont, null);
        fields.setField("Federal EducationDeductions", this.get_Federal_EducationDeductions());
        fields.setFieldProperty("Vermont EducatorExpenses", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont EducatorExpenses", "textfont", baseFont, null);
        fields.setField("Vermont EducatorExpenses", this.get_Vermont_EducatorExpenses());
        fields.setFieldProperty("NonVtIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("NonVtIncome", "textfont", baseFont, null);
        fields.setField("NonVtIncome", this.get_NonVtIncome());
        fields.setFieldProperty("Vermont Dividends", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont Dividends", "textfont", baseFont, null);
        fields.setField("Vermont Dividends", this.get_Vermont_Dividends());
        fields.setFieldProperty("Vermont CapitalGainLoss", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont CapitalGainLoss", "textfont", baseFont, null);
        fields.setField("Vermont CapitalGainLoss", this.get_Vermont_CapitalGainLoss());
        fields.setFieldProperty("Vermont TotalAdjustments", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TotalAdjustments", "textfont", baseFont, null);
        fields.setField("Vermont TotalAdjustments", this.get_Vermont_TotalAdjustments());
        fields.setFieldProperty("Vermont EmployeeDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont EmployeeDeductions", "textfont", baseFont, null);
        fields.setField("Vermont EmployeeDeductions", this.get_Vermont_EmployeeDeductions());
        fields.setFieldProperty("Vermont SelfEmploymentDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont SelfEmploymentDeductions", "textfont", baseFont, null);
        fields.setField("Vermont SelfEmploymentDeductions", this.get_Vermont_SelfEmploymentDeductions());
        fields.setFieldProperty("Vermont IRA", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont IRA", "textfont", baseFont, null);
        fields.setField("Vermont IRA", this.get_Vermont_IRA());
        fields.setFieldProperty("Vermont AlimonyReceived", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont AlimonyReceived", "textfont", baseFont, null);
        fields.setField("Vermont AlimonyReceived", this.get_Vermont_AlimonyReceived());
        fields.setFieldProperty("Federal FarmIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal FarmIncome", "textfont", baseFont, null);
        fields.setField("Federal FarmIncome", this.get_Federal_FarmIncome());
        fields.setFieldProperty("Federal HealthSavingsAccount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal HealthSavingsAccount", "textfont", baseFont, null);
        fields.setField("Federal HealthSavingsAccount", this.get_Federal_HealthSavingsAccount());
        fields.setFieldProperty("Federal EmployeeDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal EmployeeDeductions", "textfont", baseFont, null);
        fields.setField("Federal EmployeeDeductions", this.get_Federal_EmployeeDeductions());
        fields.setFieldProperty("Federal SelfEmploymentDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal SelfEmploymentDeductions", "textfont", baseFont, null);
        fields.setField("Federal SelfEmploymentDeductions", this.get_Federal_SelfEmploymentDeductions());
        fields.setFieldProperty("Federal BusinessIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal BusinessIncome", "textfont", baseFont, null);
        fields.setField("Federal BusinessIncome", this.get_Federal_BusinessIncome());
        fields.setFieldProperty("Federal WagesSalariesTips", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal WagesSalariesTips", "textfont", baseFont, null);
        fields.setField("Federal WagesSalariesTips", this.get_Federal_WagesSalariesTips());
        fields.setFieldProperty("FedEmpOpportunity", "textsize", new Float(20.2), null);
        fields.setFieldProperty("FedEmpOpportunity", "textfont", baseFont, null);
        fields.setField("FedEmpOpportunity", this.get_FedEmpOpportunity());
        fields.setFieldProperty("VtTelecommunicationAuthority", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VtTelecommunicationAuthority", "textfont", baseFont, null);
        fields.setField("VtTelecommunicationAuthority", this.get_VtTelecommunicationAuthority());
        fields.setFieldProperty("VtIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("VtIncome", "textfont", baseFont, null);
        fields.setField("VtIncome", this.get_VtIncome());
        fields.setFieldProperty("Vermont EducationDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont EducationDeductions", "textfont", baseFont, null);
        fields.setField("Vermont EducationDeductions", this.get_Vermont_EducationDeductions());
        fields.setFieldProperty("Federal TotalIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TotalIncome", "textfont", baseFont, null);
        fields.setField("Federal TotalIncome", this.get_Federal_TotalIncome());
        fields.setFieldProperty("Vermont PartnershipSCorpLLC", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont PartnershipSCorpLLC", "textfont", baseFont, null);
        fields.setField("Vermont PartnershipSCorpLLC", this.get_Vermont_PartnershipSCorpLLC());
        fields.setFieldProperty("Text29", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Text29", "textfont", baseFont, null);
        fields.setField("Text29", this.get_Text29());
        fields.setFieldProperty("Vermont TaxableIRADistributions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont TaxableIRADistributions", "textfont", baseFont, null);
        fields.setField("Vermont TaxableIRADistributions", this.get_Vermont_TaxableIRADistributions());
        fields.setFieldProperty("Federal OtherDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal OtherDeductions", "textfont", baseFont, null);
        fields.setField("Federal OtherDeductions", this.get_Federal_OtherDeductions());
        fields.setFieldProperty("Federal UnemploymentCompensation", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal UnemploymentCompensation", "textfont", baseFont, null);
        fields.setField("Federal UnemploymentCompensation", this.get_Federal_UnemploymentCompensation());
        fields.setFieldProperty("Vermont OtherDeductions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont OtherDeductions", "textfont", baseFont, null);
        fields.setField("Vermont OtherDeductions", this.get_Vermont_OtherDeductions());
        fields.setFieldProperty("Federal Dividends", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal Dividends", "textfont", baseFont, null);
        fields.setField("Federal Dividends", this.get_Federal_Dividends());
        fields.setFieldProperty("Vermont UnemploymentCompensation", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont UnemploymentCompensation", "textfont", baseFont, null);
        fields.setField("Vermont UnemploymentCompensation", this.get_Vermont_UnemploymentCompensation());
        fields.setFieldProperty("RailroadRetirement", "textsize", new Float(20.2), null);
        fields.setFieldProperty("RailroadRetirement", "textfont", baseFont, null);
        fields.setField("RailroadRetirement", this.get_RailroadRetirement());
        fields.setFieldProperty("Vermont EarlyWithdrawlSavings", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont EarlyWithdrawlSavings", "textfont", baseFont, null);
        fields.setField("Vermont EarlyWithdrawlSavings", this.get_Vermont_EarlyWithdrawlSavings());
        fields.setFieldProperty("AmericansWithDisabilities", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AmericansWithDisabilities", "textfont", baseFont, null);
        fields.setField("AmericansWithDisabilities", this.get_AmericansWithDisabilities());
        fields.setFieldProperty("Federal TaxableIRADistributions", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TaxableIRADistributions", "textfont", baseFont, null);
        fields.setField("Federal TaxableIRADistributions", this.get_Federal_TaxableIRADistributions());
        fields.setFieldProperty("Federal TotalAdjustments", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TotalAdjustments", "textfont", baseFont, null);
        fields.setField("Federal TotalAdjustments", this.get_Federal_TotalAdjustments());
        fields.setFieldProperty("AdjustedGrossIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("AdjustedGrossIncome", "textfont", baseFont, null);
        fields.setField("AdjustedGrossIncome", this.get_AdjustedGrossIncome());
        fields.setFieldProperty("Federal EarlyWithdrawlSavings", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal EarlyWithdrawlSavings", "textfont", baseFont, null);
        fields.setField("Federal EarlyWithdrawlSavings", this.get_Federal_EarlyWithdrawlSavings());
        fields.setFieldProperty("Federal TaxableInterest", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Federal TaxableInterest", "textfont", baseFont, null);
        fields.setField("Federal TaxableInterest", this.get_Federal_TaxableInterest());
        fields.setFieldProperty("Vermont HealthSavingsAccount", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont HealthSavingsAccount", "textfont", baseFont, null);
        fields.setField("Vermont HealthSavingsAccount", this.get_Vermont_HealthSavingsAccount());
        fields.setFieldProperty("Vermont FarmIncome", "textsize", new Float(20.2), null);
        fields.setFieldProperty("Vermont FarmIncome", "textfont", baseFont, null);
        fields.setField("Vermont FarmIncome", this.get_Vermont_FarmIncome());
        stamper.setFormFlattening(true);
        stamper.setFullCompression();
        for (int i = 0; i < reader.getNumberOfPages() + 1; i++) {
            PdfContentByte overContent = stamper.getOverContent(i);
            if (overContent != null) {
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES_ITALIC);
                font.setColor(BaseColor.BLUE);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.BLUE);
                overContent.setFontAndSize(baseFont, 24);
                overContent.showTextAligned(Element.ALIGN_RIGHT | Element.ALIGN_TOP, "Electronically filed via Modernized eFile", 20, 175, 90);
                overContent.endText();
                overContent.beginText();
                font = FontFactory.getFont(FontFactory.TIMES);
                font.setColor(BaseColor.RED);
                baseFont = font.getBaseFont();
                overContent.setColorFill(BaseColor.RED);
                overContent.setFontAndSize(baseFont, 8);
                overContent.showTextAligned(Element.ALIGN_CENTER | Element.ALIGN_BOTTOM, "Retrieved by " + user + " on " + new Date().toString(), 220, 3, 0);
                overContent.endText();
            }
        }
        stamper.close();
        reader.close();
    }
}
